apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    isDefault: true
    # Use environment variable substitution during container startup or CI templating
    url: ${PROMETHEUS_URL}
    basicAuth: false
    editable: true
